# -*- coding: utf-8 -*-
"""[w6]가장긴증가하는부분수열4_14002.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CEIGWQfJc2dufm8gXsX7x4ZAWc14Ft5b
"""

N=int(input())
A=list(map(int,input().split()))

dp=[1]*N # 초기값을 1로 세팅해야함
for i in range(1,N):
    for j in range(i):
        if A[i]>A[j]:
            dp[i]=max(dp[i],dp[j]+1)

print(max(dp))

arr = []
max = max(dp)
for i in range(N - 1, -1, -1):
    if dp[i] == max:
        arr.append(A[i])
        max -= 1

arr.reverse()
print(*arr)