# -*- coding: utf-8 -*-
"""[w6]이진수_2193.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uzy_5zEjfkwa9lM2ukDa8WbX9oPIqMZe
"""

N = int(input())

dp = [0] * (N + 1)
dp[1] = 1

for i in range(2, N+1):
    dp[i] = dp[i-2] + dp[i-1]

print(dp[N])