# -*- coding: utf-8 -*-
"""[w6]카드구매하기2_16194.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pL3ijxcCvYWgi-dEZi4bX2klrpVPTxpz
"""

N = int(input())
P = [0] + list(map(int,input().split()))
DP = [False for _ in range(N+1)]

for i in range(1, N+1): # 1부터 N까지
    for j in range(1, i+1):
      if DP[i] == False:
          DP[i] = DP[i-j] + P[j]
      else:
          DP[i] = min(DP[i], DP[i-j] + P[j])

print(DP[N])