# -*- coding: utf-8 -*-
"""[w6]쉬운계단수_10844.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wDv0302E7Cy_kDaf1ZSN6x2wNFcir-4v
"""

N = int(input())

dp = [[0]*10 for _ in range(N+1)]
for i in range(1, 10): # 1의 자리 수는 초기화
    dp[1][i] = 1

MOD = 1000000000

for i in range(2, N+1):
    for j in range(10):
        if j == 0:
            dp[i][j] = dp[i-1][1]
        elif j == 9:
            dp[i][j] = dp[i-1][8]
        else:
            dp[i][j] = dp[i-1][j-1] + dp[i-1][j+1]

print(sum(dp[N]) % MOD)