# -*- coding: utf-8 -*-
"""[w6]가장긴증가하는부분수열_11053.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XpqCK-YRoPdBgS2pBkJmvOvV3W7qSBZN
"""

N=int(input())
A=list(map(int,input().split()))

dp=[1]*N # 초기값을 1로 세팅해야함
for i in range(1,N):
    for j in range(i):
        if A[i]>A[j]:
            dp[i]=max(dp[i],dp[j]+1)

print(max(dp))

