# -*- coding: utf-8 -*-
"""[w5]123더하기_9095.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UestJ8HAS9uWOh3mG8tMS2vNXLQzI290
"""

T = int(input())

for _ in range(T):
    N = int(input())
    dp = [0] * (N + 1)

    for i in range(1, N+1):
        if i == 1:
            dp[i] = 1
        elif i == 2:
            dp[i] = 2
        elif i == 3:
            dp[i] = 4
        else:
            dp[i] = dp[i-1] + dp[i-2] + dp[i-3]

    print(dp[N])