# -*- coding: utf-8 -*-
"""[w5]1로만들기_1463.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nzLkaQjnns2cu9U7jJ1MbYw21n8uTkoB
"""

N = int(input())
dp=[0]*(N+1)

for i in range(2,N+1): # 2부터 N까지 반복
    dp[i]=dp[i-1]+1 # 1을 빼는 연산 -> 1회 진행
    if i%2==0: # 2로 나누어 떨어질 때, 2로 나누는 연산
        dp[i]=min(dp[i],dp[i//2]+1)
    if i%3==0: # 3으로 나누어 떨어질 때, 3으로 나누는 연산
        dp[i]=min(dp[i],dp[i//3]+1)

print(dp[N])