# -*- coding: utf-8 -*-
"""[w5]2xn타일링2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IhIV1NspRYp7_Ux6i0eRipNX2gC938rZ
"""

N = int(input())
dp=[0]*(N+1)
dp[0] = 1
dp[1] = 1

for i in range(2,N+1):
    dp[i] = dp[i-1] + 2 * dp[i-2]

print(dp[N] % 10007)