# -*- coding: utf-8 -*-
"""[W8]동물원_1309.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oeTIftrB3L2cBhtyimNopmtTYef4ijaw
"""

N = int(input())

DP = [[0]*3 for _ in range(N+1)]
DP[1][0] = 1
DP[1][1] = 1
DP[1][2] = 1

for i in range(2, N+1):
    DP[i][0] = (DP[i-1][0] + DP[i-1][1] + DP[i-1][2]) % 9901
    DP[i][1] = (DP[i-1][0] + DP[i-1][2]) % 9901
    DP[i][2] = (DP[i-1][0] + DP[i-1][1]) % 9901

print(sum(DP[N]) % 9901)