# -*- coding: utf-8 -*-
"""[W8]오르막수_11057.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ncGy9AcDv_Z9Tt6sFgNjKS8uIgo8UrK_
"""

N = int(input())
DP = [1]*10

for i in range(1, N) :
    for j in range(1, 10) :
        DP[j] += DP[j-1]

print(sum(DP)%10007)