# -*- coding: utf-8 -*-
"""[W8]스티커_9465.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zmSEnIM80ydywaOC9HddCvpXIJ9dwolB
"""

T = int(input())

for _ in range(T):
    N = int(input())
    DP = [list(map(int, input().split())) for _ in range(2)]

    DP[0][1] += DP[1][0]
    DP[1][1] += DP[0][0]

    for i in range(2, N):
        DP[0][i] += max(DP[1][i-1], DP[1][i-2])
        DP[1][i] += max(DP[0][i-1], DP[0][i-2])

    print(max(DP[0][N-1], DP[1][N-1]))