# -*- coding: utf-8 -*-
"""[W8]RGB거리_1149.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1apTKHp1dtt30lE4w94O9ujO0fGjRzZtf
"""

N = int(input())
arr = [list(map(int, input().split())) for _ in range(N)]
DP = [[0]*3 for _ in range(N)]
DP[0] = arr[0]

for i in range(1, N):
    DP[i][0] = min(DP[i-1][1], DP[i-1][2]) + arr[i][0]
    DP[i][1] = min(DP[i-1][0], DP[i-1][2]) + arr[i][1]
    DP[i][2] = min(DP[i-1][0], DP[i-1][1]) + arr[i][2]

print(min(DP[N-1]))