# -*- coding: utf-8 -*-
"""[W8]포도주시식_2156.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qwZ6PynwuTUWmVj3YRT9J-tqikyhxtzD
"""

N = int(input())

wine = [int(input()) for _ in range(N)]

DP = [0]*N

DP[0] = wine[0]
if N > 1:
    DP[1] = wine[0]+wine[1]

if N > 2:
    DP[2] = max(wine[2]+wine[1], wine[2]+wine[0], DP[1])

for i in range(3, N):
    DP[i] = max(DP[i-1], DP[i-3]+wine[i-1]+wine[i], DP[i-2]+wine[i])

print(DP[N-1])